sonar.projectKey=zzonni_technical-debt-demo
sonar.organization=zzonni
sonar.newCode.referenceBranch=main
sonar.qualitygate.wait=true

# This is the name and version displayed in the SonarCloud UI.
sonar.projectName=technical-debt-demo
sonar.projectVersion=1.0

# Path is relative to the sonar-project.properties file. Replace "\" by "/" on Windows.
sonar.sources=.

# Exclude test files from source analysis
sonar.exclusions=tests/**

# Test coverage
sonar.python.coverage.reportPaths=coverage.xml
sonar.tests=tests
sonar.test.inclusions=tests/**/*.py
# Encoding of the source code. Default is default system encoding
sonar.sourceEncoding=UTF-8
